// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlNvN88tHLtLwIp9CmxGD8oQJ_nLyWw2s',
    appId: '1:1094735001374:web:606bd3f88488901afa7b0f',
    messagingSenderId: '1094735001374',
    projectId: 'eldcare-c1ac4',
    authDomain: 'eldcare-c1ac4.firebaseapp.com',
    storageBucket: 'eldcare-c1ac4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj9P_NjUsuC_kneBFwAumosxi6gnyoOSM',
    appId: '1:1094735001374:android:a9368c0a54a27481fa7b0f',
    messagingSenderId: '1094735001374',
    projectId: 'eldcare-c1ac4',
    storageBucket: 'eldcare-c1ac4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2JhHoU5ecdBH5Q7jH9AZjvKE63y1BM-E',
    appId: '1:1094735001374:ios:60fdaf3fd0465342fa7b0f',
    messagingSenderId: '1094735001374',
    projectId: 'eldcare-c1ac4',
    storageBucket: 'eldcare-c1ac4.appspot.com',
    iosBundleId: 'com.example.eldcare',
  );
}
